version: '3'

services:
  app:
    # This approach would build new image tagged as repository on every docker compose
    # up command with latest version
    image: activity-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: analytics
    ports:
      - 5440:5432
    volumes:
      - db-data:/var/lib/postgresql/anal_data
